<a href="https://colab.research.google.com/github/milkywayweaver/learn_pytorch/blob/main/course/PyT_C001_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PyTorch for Deep Learning & Machine Learning: Fundamentals** <br>
<br>
📖 Course: <br>
 PyTorch for Deep Learning & Machine Learning - freeCodeCamp.org, taught by Daniel Bourke. <br>
https://youtu.be/V_xro1bcAuA?si=luBE0ln8qKDfQWyM

In [1]:
import torch
print(torch.__version__)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# RANDOM_SEED = 16
# torch.manual_seed(RANDOM_SEED)

2.6.0+cu124


🔑 To change the hardware accelerator to GPU, go to runtime > change runtime type.

In [2]:
!nvidia-smi

Tue May 27 04:28:31 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   48C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# Making Tensors

💡 **INTRODUCTION TO TENSOR** <br>
1. Scalar : Tensor of rank 0
2. Vector : Tensor of rank 1
2. MATRIX : Tensor of rank 2
3. TENSOR : Tensor of rank >2

In [3]:
# Scalar
scalar = torch.tensor(4)
display(scalar)

# Get the item as Python int
display(scalar.item())

# Get the shape and rank
display(scalar.shape)
display(scalar.ndim)

tensor(4)

4

torch.Size([])

0

In [4]:
# Vector
vector = torch.tensor([4,1,6])
display(vector)

# Get the shape and rank
display(vector.shape,vector.ndim)

tensor([4, 1, 6])

torch.Size([3])

1

In [5]:
# MATRIX
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6]])
display(MATRIX)

# Get the shape and rank
display(MATRIX.shape,MATRIX.ndim)

tensor([[1, 2, 3],
        [4, 5, 6]])

torch.Size([2, 3])

2

In [6]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
display(TENSOR)

# Get the shape and rank
display(TENSOR.shape,TENSOR.ndim)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

torch.Size([1, 3, 3])

3

💡 **RANDOM TENSOR**

In [7]:
RANDOM = torch.rand(3,4)
RANDOM

tensor([[0.4557, 0.0795, 0.0556, 0.7876],
        [0.0600, 0.4706, 0.9320, 0.7877],
        [0.8616, 0.0756, 0.7317, 0.0840]])

In [8]:
np_random = np.random.randint(0,10,20)
NUMPY_RANDOM = torch.tensor(np_random).reshape(4,5)
NUMPY_RANDOM

tensor([[3, 9, 8, 3, 5],
        [8, 2, 4, 1, 7],
        [7, 6, 4, 5, 1],
        [4, 5, 9, 0, 2]])

💡**ZEROS, ONES, ARANGE**

In [9]:
# Zeros
zeros = torch.zeros(3,4)
display(zeros)

# Zeros-Like - Make zeros tensor in the shape of another tensor
zeros_2 = torch.zeros_like(TENSOR)
display(zeros_2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [10]:
# Ones
ones = torch.ones(3,4)
display(ones)

# Ones-Like - Make ones tensor in the shape of another tensor
ones_2 = torch.ones_like(TENSOR)
display(ones_2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])

In [11]:
# Range
ranges = torch.arange(0,111,11)
ranges

tensor([  0,  11,  22,  33,  44,  55,  66,  77,  88,  99, 110])

# Tensor Informations

💡 **DATATYPE**

In [12]:
float_32_tensor = torch.tensor([0.0,1.0,6.0],
                               dtype=torch.float32, # 'torch.float16, torch.float64, ...
                               device = None, # 'cpu', 'cuda', ...
                               requires_grad=False) # bool - tracks gradient
float_32_tensor.dtype

torch.float32

In [13]:
# Change datatype
int_16_tensor = float_32_tensor.type(torch.int16)
int_16_tensor.dtype

torch.int16

In [14]:
# Operations with other datatypes --> Changes datatype to the more complex datatype
(int_16_tensor * float_32_tensor).dtype

torch.float32

💡 **GETTING INFORMATION FROM TENSORS** <br>
3 major sources of errors in PyTorch/Deep Learning:
1. Tensor datatype
2. Tensor shape
3. Tensor device

In [15]:
display(TENSOR)

# Shape
display(TENSOR.dtype)

# Shape
display(TENSOR.shape)
# TENSOR.size() also works the same

# Device
display(TENSOR.device)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

torch.int64

torch.Size([1, 3, 3])

device(type='cpu')

# Tensor Operations

💡 **TENSOR OPERATIONS**

In [16]:
np.random.seed(42)
A = torch.tensor(np.random.randint(0,10,12)).reshape(3,4)
B = torch.tensor(np.random.randint(0,10,12)).reshape(3,4)

A,B

(tensor([[6, 3, 7, 4],
         [6, 9, 2, 6],
         [7, 4, 3, 7]]),
 tensor([[7, 2, 5, 4],
         [1, 7, 5, 1],
         [4, 0, 9, 5]]))

In [17]:
# Addition/Subtraction
A + B - 2

tensor([[11,  3, 10,  6],
        [ 5, 14,  5,  5],
        [ 9,  2, 10, 10]])

In [18]:
# Element-wise multiplication/Division
A * B / 2

tensor([[21.0000,  3.0000, 17.5000,  8.0000],
        [ 3.0000, 31.5000,  5.0000,  3.0000],
        [14.0000,  0.0000, 13.5000, 17.5000]])

In [19]:
# Matrix multiplication
np.random.seed(42)
A = torch.tensor(np.random.randint(0,10,12)).reshape(3,4)
B = torch.tensor(np.random.randint(0,10,12)).reshape(4,3)

A,B

(tensor([[6, 3, 7, 4],
         [6, 9, 2, 6],
         [7, 4, 3, 7]]),
 tensor([[7, 2, 5],
         [4, 1, 7],
         [5, 1, 4],
         [0, 9, 5]]))

In [20]:
A@B

tensor([[ 89,  58,  99],
        [ 88,  77, 131],
        [ 80,  84, 110]])

# Reshaping Tensors

💡 **TRANSPOSE, RESHAPE, SQUEEZE, AND STACK** <br>
1. Transpose switches the axis around
2. Reshape simply reshapes the tensor while keeping the element order the same
3. Squueze removes single dimensions from the tensor
4. Stack combines multiple tensors

In [21]:
np.random.seed(42)
A = torch.tensor(np.random.randint(0,10,12)).reshape(3,4)
B = torch.tensor(np.random.randint(0,10,12)).reshape(3,4)

A,B

(tensor([[6, 3, 7, 4],
         [6, 9, 2, 6],
         [7, 4, 3, 7]]),
 tensor([[7, 2, 5, 4],
         [1, 7, 5, 1],
         [4, 0, 9, 5]]))

In [22]:
# Transpose
display(A.T)
display(A.T.shape)

tensor([[6, 6, 7],
        [3, 9, 4],
        [7, 2, 3],
        [4, 6, 7]])

torch.Size([4, 3])

In [23]:
# Reshape
display(A.reshape(4,3))
display(A.reshape(4,3).shape)

tensor([[6, 3, 7],
        [4, 6, 9],
        [2, 6, 7],
        [4, 3, 7]])

torch.Size([4, 3])

In [24]:
# Squeeze
C = torch.tensor([[[1,2,3,4,5],[6,7,8,9,10]]])
display(C,C.shape)
print('\n')
C_squueze = C.squeeze()
display(C_squueze,C_squueze.shape)

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]])

torch.Size([1, 2, 5])

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

torch.Size([2, 5])

In [25]:
# Unsquueze : adds single dimension along specified axis
C_unsqueeze = C_squueze.unsqueeze(1)
C_unsqueeze, C_unsqueeze.shape

(tensor([[[ 1,  2,  3,  4,  5]],
 
         [[ 6,  7,  8,  9, 10]]]),
 torch.Size([2, 1, 5]))

In [26]:
# Stacks tensor along specified axis
AB = torch.stack([A,B],1)
AB

tensor([[[6, 3, 7, 4],
         [7, 2, 5, 4]],

        [[6, 9, 2, 6],
         [1, 7, 5, 1]],

        [[7, 4, 3, 7],
         [4, 0, 9, 5]]])

In [27]:
# Vertical stack
torch.vstack([A,B])

tensor([[6, 3, 7, 4],
        [6, 9, 2, 6],
        [7, 4, 3, 7],
        [7, 2, 5, 4],
        [1, 7, 5, 1],
        [4, 0, 9, 5]])

In [28]:
# Horizontal stack
torch.hstack([A,B])

tensor([[6, 3, 7, 4, 7, 2, 5, 4],
        [6, 9, 2, 6, 1, 7, 5, 1],
        [7, 4, 3, 7, 4, 0, 9, 5]])

In [29]:
# Permute : returns a view in a re-aranged axis
# A view shares the same channel as the original one, meaning  changes in the view would affect the original tensor
IMG = torch.rand(size=(224,224,3)) # H,W,RGB
IMG_permuted = IMG.permute(2,0,1)
IMG_permuted.shape # RGB,H,W

torch.Size([3, 224, 224])

# Tensor Aggregation

💡 **TENSOR AGGREGATION**

In [30]:
np.random.seed(42)
A = torch.tensor(np.random.randint(0,10,12)).reshape(3,4)
B = torch.tensor(np.random.randint(0,10,12)).reshape(3,4)

A,B

(tensor([[6, 3, 7, 4],
         [6, 9, 2, 6],
         [7, 4, 3, 7]]),
 tensor([[7, 2, 5, 4],
         [1, 7, 5, 1],
         [4, 0, 9, 5]]))

In [31]:
# Find the min
display(torch.min(A))
display(A.min())

tensor(2)

tensor(2)

In [32]:
# Find the max
display(torch.max(A))
display(A.max())

tensor(9)

tensor(9)

In [33]:
# Find the mean
# !!! Mean only works with float or complex datatype !!!
display(torch.mean(A.type(torch.float32)))
display(A.type(torch.float32).mean())

tensor(5.3333)

tensor(5.3333)

In [34]:
# Find the sum
display(torch.sum(A))
display(A.sum())

tensor(64)

tensor(64)

In [35]:
# Find the stdev
display(torch.std(A.type(torch.float32)))
display(A.type(torch.float32).std())

tensor(2.1034)

tensor(2.1034)

In [36]:
# Find the positional min/max
display(A)
print('\n')
display(torch.argmin(A,0)) # Find the minimum location in the 0th axis
display(A.argmin(1)) # Find the minimum location in the 1st axis

tensor([[6, 3, 7, 4],
        [6, 9, 2, 6],
        [7, 4, 3, 7]])

tensor([0, 0, 1, 0])

tensor([1, 2, 2])

# Interaction with Numpy

In [37]:
np.random.seed(16)

np_array = np.random.randint(0,10,12)
# Numpy array to PyTorch tensor
A = torch.tensor(np_array,dtype=torch.float32).reshape(3,4)
B = torch.from_numpy(np_array).reshape(3,4).type(torch.float32)

display(A)
display(B)

tensor([[9., 9., 5., 1.],
        [4., 4., 9., 0.],
        [0., 8., 2., 4.]])

tensor([[9., 9., 5., 1.],
        [4., 4., 9., 0.],
        [0., 8., 2., 4.]])

In [38]:
A.numpy()

array([[9., 9., 5., 1.],
       [4., 4., 9., 0.],
       [0., 8., 2., 4.]], dtype=float32)

# Using PyTroch with GPU

In [39]:
!nvidia-smi

Tue May 27 04:28:32 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   48C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [40]:
torch.cuda.is_available()

True

In [41]:
# Setup device agnosic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [42]:
# Count of GPUs
torch.cuda.device_count()

1

In [43]:
# Putting tensor on a GPU\

A = torch.randn(size=(4,3))
display(A)
display(A.device)
print('\n')

# Moving tensor to GPU
A_GPU = A.to(device)
display(A_GPU)
display(A_GPU.device)

tensor([[-0.1452, -1.4190, -0.1203],
        [ 0.4060, -0.0711,  0.2325],
        [-0.7044,  1.5600, -0.5783],
        [-0.3500, -0.7844,  0.2953]])

device(type='cpu')

tensor([[-0.1452, -1.4190, -0.1203],
        [ 0.4060, -0.0711,  0.2325],
        [-0.7044,  1.5600, -0.5783],
        [-0.3500, -0.7844,  0.2953]], device='cuda:0')

device(type='cuda', index=0)

In [44]:
# Moving tensor back to CPU
# NumPy cant process tensor thas on a GPU

A_GPU.cpu().numpy()

array([[-0.14523257, -1.418966  , -0.12026791],
       [ 0.40604582, -0.07111763,  0.23252818],
       [-0.70441246,  1.5599576 , -0.5782523 ],
       [-0.35001722, -0.78442484,  0.2953222 ]], dtype=float32)